USE ROLE accountadmin;

CREATE OR REPLACE WAREHOUSE PNL_WAREHOUSE_DBT_WH
    WAREHOUSE_SIZE = 'small'
    WAREHOUSE_TYPE = 'standard'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'warehouse for pnl warehouse';

USE WAREHOUSE PNL_WAREHOUSE_DBT_WH;

CREATE DATABASE IF NOT EXISTS BLUECREST_WAREHOUSE;
CREATE OR REPLACE SCHEMA BLUECREST_WAREHOUSE.RAW;
CREATE OR REPLACE SCHEMA BLUECREST_WAREHOUSE.DEV;
CREATE OR REPLACE SCHEMA BLUECREST_WAREHOUSE.PRD;


ALTER SCHEMA BLUECREST_WAREHOUSE.DEV SET LOG_LEVEL = 'INFO';
ALTER SCHEMA BLUECREST_WAREHOUSE.DEV SET TRACE_LEVEL = 'ALWAYS';
ALTER SCHEMA BLUECREST_WAREHOUSE.DEV SET METRIC_LEVEL = 'ALL';

ALTER SCHEMA BLUECREST_WAREHOUSE.PRD SET LOG_LEVEL = 'INFO';
ALTER SCHEMA BLUECREST_WAREHOUSE.PRD SET TRACE_LEVEL = 'ALWAYS';
ALTER SCHEMA BLUECREST_WAREHOUSE.PRD SET METRIC_LEVEL = 'ALL';

CREATE OR REPLACE API INTEGRATION GITHUB_INTEGRATION
API_PROVIDER = git_https_api
API_ALLOWED_PREFIXES = ('https://github.com')
API_USER_AUTHENTICATION = (TYPE = snowflake_github_app)
ENABLED = TRUE;

CREATE OR REPLACE NETWORK RULE BLUECREST_WAREHOUSE.public.dbt_network_rule
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('hub.getdbt.com', 'codeload.github.com');

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION dbt_access_integration
  ALLOWED_NETWORK_RULES = (BLUECREST_WAREHOUSE.public.dbt_network_rule)
  ENABLED = true;

-- setup completion note
SELECT 'BLUECREST_WAREHOUSE setup is now complete' AS note;
