name: pnl_warehouse
version: 1.0.0
config-version: 2
profile: pnl_warehouse
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  pnl_warehouse:
    +materialized: view
