pnl_warehouse:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: ACCOUNTADMIN
      warehouse: PNL_WAREHOUSE_DBT_WH
      database: BLUECREST_WAREHOUSE
      schema: DEV
      account: 'not needed'
      user: 'not needed'
    prod:
      type: snowflake
      role: ACCOUNTADMIN
      warehouse: PNL_WAREHOUSE_DBT_WH
      database: BLUECREST_WAREHOUSE
      schema: PRD
      account: 'not needed'
      user: 'not needed'
